/*
###############################################################
#  Generated by:      Cadence Innovus 16.12-s051_1
#  OS:                Linux x86_64(Host ID ee215lnx10.ecn.purdue.edu)
#  Generated on:      Tue Mar  7 12:51:42 2017
#  Design:            lab7_layout_design
#  Command:           saveNetlist -excludeLeafCell final.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : K-2015.06-SP1
// Date      : Tue Feb 28 11:18:12 2017
/////////////////////////////////////////////////////////////
module lab7_out_ctrl (
	clk, 
	n_rst, 
	d_plus, 
	d_minus, 
	bus_mode, 
	tx_value);
   input clk;
   input n_rst;
   output d_plus;
   output d_minus;
   input [1:0] bus_mode;
   input tx_value;

   // Internal wires
   wire FE_OFN0_nd_minus;
   wire n10;
   wire n11;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;

   BUFX2 FE_OFC0_nd_minus (.A(FE_OFN0_nd_minus),
	.Y(d_minus));
   DFFSR d_minus_reg_reg (.CLK(clk),
	.D(n11),
	.Q(FE_OFN0_nd_minus),
	.R(n_rst),
	.S(1'b1));
   DFFSR d_plus_reg_reg (.CLK(clk),
	.D(n10),
	.Q(d_plus),
	.R(1'b1),
	.S(n_rst));
   NOR2X1 U5 (.A(n3),
	.B(n4),
	.Y(n11));
   MUX2X1 U6 (.A(d_minus),
	.B(n5),
	.S(bus_mode[1]),
	.Y(n4));
   INVX1 U7 (.A(tx_value),
	.Y(n5));
   MUX2X1 U8 (.A(n7),
	.B(n6),
	.S(bus_mode[1]),
	.Y(n10));
   NAND2X1 U9 (.A(d_plus),
	.B(bus_mode[0]),
	.Y(n7));
   NOR2X1 U10 (.A(tx_value),
	.B(n3),
	.Y(n6));
   INVX1 U11 (.A(bus_mode[0]),
	.Y(n3));
endmodule

module lab7_encoder (
	clk, 
	n_rst, 
	tx_bit, 
	shift_enable, 
	tx_value);
   input clk;
   input n_rst;
   input tx_bit;
   input shift_enable;
   output tx_value;

   // Internal wires
   wire last_bit;
   wire n1;
   wire n2;

   DFFSR last_bit_reg (.CLK(clk),
	.D(n2),
	.Q(last_bit),
	.R(1'b1),
	.S(n_rst));
   XNOR2X1 U2 (.A(last_bit),
	.B(tx_bit),
	.Y(tx_value));
   INVX1 U3 (.A(n1),
	.Y(n2));
   MUX2X1 U4 (.A(tx_bit),
	.B(last_bit),
	.S(shift_enable),
	.Y(n1));
endmodule

module lab7_tx_sr_1 (
	clk, 
	n_rst, 
	shift_enable, 
	tx_enable, 
	tx_data, 
	load_data, 
	tx_out);
   input clk;
   input n_rst;
   input shift_enable;
   input tx_enable;
   input [7:0] tx_data;
   input load_data;
   output tx_out;

   // Internal wires
   wire FE_OFN3_n13;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire [7:1] curr_val;

   BUFX2 FE_OFC3_n13 (.A(n13),
	.Y(FE_OFN3_n13));
   DFFSR \curr_val_reg[7]  (.CLK(clk),
	.D(n30),
	.Q(curr_val[7]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[6]  (.CLK(clk),
	.D(n31),
	.Q(curr_val[6]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[5]  (.CLK(clk),
	.D(n32),
	.Q(curr_val[5]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[4]  (.CLK(clk),
	.D(n33),
	.Q(curr_val[4]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[3]  (.CLK(clk),
	.D(n34),
	.Q(curr_val[3]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[2]  (.CLK(clk),
	.D(n35),
	.Q(curr_val[2]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[1]  (.CLK(clk),
	.D(n36),
	.Q(curr_val[1]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[0]  (.CLK(clk),
	.D(n29),
	.Q(tx_out),
	.R(n_rst),
	.S(1'b1));
   OAI21X1 U11 (.A(n9),
	.B(n10),
	.C(n11),
	.Y(n36));
   AOI22X1 U12 (.A(curr_val[2]),
	.B(n12),
	.C(curr_val[1]),
	.D(FE_OFN3_n13),
	.Y(n11));
   INVX1 U13 (.A(tx_data[1]),
	.Y(n10));
   OAI21X1 U14 (.A(n9),
	.B(n14),
	.C(n15),
	.Y(n35));
   AOI22X1 U15 (.A(curr_val[3]),
	.B(n12),
	.C(FE_OFN3_n13),
	.D(curr_val[2]),
	.Y(n15));
   INVX1 U16 (.A(tx_data[2]),
	.Y(n14));
   OAI21X1 U17 (.A(n9),
	.B(n16),
	.C(n17),
	.Y(n34));
   AOI22X1 U18 (.A(curr_val[4]),
	.B(n12),
	.C(curr_val[3]),
	.D(FE_OFN3_n13),
	.Y(n17));
   INVX1 U19 (.A(tx_data[3]),
	.Y(n16));
   OAI21X1 U20 (.A(n9),
	.B(n18),
	.C(n19),
	.Y(n33));
   AOI22X1 U21 (.A(curr_val[5]),
	.B(n12),
	.C(curr_val[4]),
	.D(FE_OFN3_n13),
	.Y(n19));
   INVX1 U22 (.A(tx_data[4]),
	.Y(n18));
   OAI21X1 U23 (.A(n9),
	.B(n20),
	.C(n21),
	.Y(n32));
   AOI22X1 U24 (.A(curr_val[6]),
	.B(n12),
	.C(curr_val[5]),
	.D(FE_OFN3_n13),
	.Y(n21));
   INVX1 U25 (.A(tx_data[5]),
	.Y(n20));
   OAI21X1 U26 (.A(n9),
	.B(n22),
	.C(n23),
	.Y(n31));
   AOI22X1 U27 (.A(curr_val[7]),
	.B(n12),
	.C(curr_val[6]),
	.D(FE_OFN3_n13),
	.Y(n23));
   INVX1 U28 (.A(tx_data[6]),
	.Y(n22));
   NAND2X1 U29 (.A(n24),
	.B(n25),
	.Y(n30));
   INVX1 U30 (.A(n12),
	.Y(n25));
   MUX2X1 U31 (.A(curr_val[7]),
	.B(tx_data[7]),
	.S(FE_OFN3_n13),
	.Y(n24));
   OAI21X1 U32 (.A(n9),
	.B(n26),
	.C(n27),
	.Y(n29));
   AOI22X1 U33 (.A(curr_val[1]),
	.B(n12),
	.C(tx_out),
	.D(FE_OFN3_n13),
	.Y(n27));
   NOR2X1 U34 (.A(FE_OFN3_n13),
	.B(load_data),
	.Y(n12));
   AOI21X1 U35 (.A(tx_enable),
	.B(shift_enable),
	.C(load_data),
	.Y(n13));
   INVX1 U36 (.A(tx_data[0]),
	.Y(n26));
   INVX1 U37 (.A(load_data),
	.Y(n9));
endmodule

module lab7_tx_sr_0 (
	clk, 
	n_rst, 
	shift_enable, 
	tx_enable, 
	tx_data, 
	load_data, 
	tx_out);
   input clk;
   input n_rst;
   input shift_enable;
   input tx_enable;
   input [7:0] tx_data;
   input load_data;
   output tx_out;

   // Internal wires
   wire FE_OFN16_n12;
   wire FE_OFN4_n13;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire [7:1] curr_val;

   BUFX2 FE_OFC16_n12 (.A(n12),
	.Y(FE_OFN16_n12));
   BUFX2 FE_OFC4_n13 (.A(n13),
	.Y(FE_OFN4_n13));
   DFFSR \curr_val_reg[7]  (.CLK(clk),
	.D(n41),
	.Q(curr_val[7]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[6]  (.CLK(clk),
	.D(n40),
	.Q(curr_val[6]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[5]  (.CLK(clk),
	.D(n39),
	.Q(curr_val[5]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[4]  (.CLK(clk),
	.D(n38),
	.Q(curr_val[4]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[3]  (.CLK(clk),
	.D(n37),
	.Q(curr_val[3]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[2]  (.CLK(clk),
	.D(n36),
	.Q(curr_val[2]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[1]  (.CLK(clk),
	.D(n28),
	.Q(curr_val[1]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_val_reg[0]  (.CLK(clk),
	.D(n42),
	.Q(tx_out),
	.R(n_rst),
	.S(1'b1));
   OAI21X1 U11 (.A(n9),
	.B(n10),
	.C(n11),
	.Y(n28));
   AOI22X1 U12 (.A(curr_val[2]),
	.B(FE_OFN16_n12),
	.C(curr_val[1]),
	.D(FE_OFN4_n13),
	.Y(n11));
   INVX1 U13 (.A(tx_data[1]),
	.Y(n10));
   OAI21X1 U14 (.A(n9),
	.B(n14),
	.C(n15),
	.Y(n36));
   AOI22X1 U15 (.A(curr_val[3]),
	.B(FE_OFN16_n12),
	.C(FE_OFN4_n13),
	.D(curr_val[2]),
	.Y(n15));
   INVX1 U16 (.A(tx_data[2]),
	.Y(n14));
   OAI21X1 U17 (.A(n9),
	.B(n16),
	.C(n17),
	.Y(n37));
   AOI22X1 U18 (.A(curr_val[4]),
	.B(FE_OFN16_n12),
	.C(curr_val[3]),
	.D(FE_OFN4_n13),
	.Y(n17));
   INVX1 U19 (.A(tx_data[3]),
	.Y(n16));
   OAI21X1 U20 (.A(n9),
	.B(n18),
	.C(n19),
	.Y(n38));
   AOI22X1 U21 (.A(curr_val[5]),
	.B(FE_OFN16_n12),
	.C(curr_val[4]),
	.D(FE_OFN4_n13),
	.Y(n19));
   INVX1 U22 (.A(tx_data[4]),
	.Y(n18));
   OAI21X1 U23 (.A(n9),
	.B(n20),
	.C(n21),
	.Y(n39));
   AOI22X1 U24 (.A(curr_val[6]),
	.B(FE_OFN16_n12),
	.C(curr_val[5]),
	.D(FE_OFN4_n13),
	.Y(n21));
   INVX1 U25 (.A(tx_data[5]),
	.Y(n20));
   OAI21X1 U26 (.A(n9),
	.B(n22),
	.C(n23),
	.Y(n40));
   AOI22X1 U27 (.A(curr_val[7]),
	.B(FE_OFN16_n12),
	.C(curr_val[6]),
	.D(FE_OFN4_n13),
	.Y(n23));
   INVX1 U28 (.A(tx_data[6]),
	.Y(n22));
   NAND2X1 U29 (.A(n24),
	.B(n25),
	.Y(n41));
   INVX1 U30 (.A(FE_OFN16_n12),
	.Y(n25));
   MUX2X1 U31 (.A(curr_val[7]),
	.B(tx_data[7]),
	.S(FE_OFN4_n13),
	.Y(n24));
   OAI21X1 U32 (.A(n9),
	.B(n26),
	.C(n27),
	.Y(n42));
   AOI22X1 U33 (.A(curr_val[1]),
	.B(FE_OFN16_n12),
	.C(tx_out),
	.D(FE_OFN4_n13),
	.Y(n27));
   NOR2X1 U34 (.A(FE_OFN4_n13),
	.B(load_data),
	.Y(n12));
   AOI21X1 U35 (.A(tx_enable),
	.B(shift_enable),
	.C(load_data),
	.Y(n13));
   INVX1 U36 (.A(tx_data[0]),
	.Y(n26));
   INVX1 U37 (.A(load_data),
	.Y(n9));
endmodule

module fiforam (
	wclk, 
	wenable, 
	waddr, 
	raddr, 
	wdata, 
	rdata);
   input wclk;
   input wenable;
   input [2:0] waddr;
   input [2:0] raddr;
   input [7:0] wdata;
   output [7:0] rdata;

   // Internal wires
   wire FE_OFN25_n241;
   wire FE_OFN24_n223;
   wire FE_OFN23_n203;
   wire FE_OFN22_n183;
   wire FE_OFN21_n250;
   wire FE_OFN20_n232;
   wire FE_OFN19_n214;
   wire FE_OFN18_n190;
   wire FE_OFN14_n175;
   wire FE_OFN13_n174;
   wire FE_OFN12_n173;
   wire FE_OFN11_n172;
   wire FE_OFN10_n56;
   wire FE_OFN9_n55;
   wire FE_OFN8_n54;
   wire FE_OFN7_n53;
   wire FE_OFN6_raddr_0;
   wire FE_OFN5_waddr_0;
   wire N11;
   wire N12;
   wire N14;
   wire N15;
   wire \fiforeg[0][7] ;
   wire \fiforeg[0][6] ;
   wire \fiforeg[0][5] ;
   wire \fiforeg[0][4] ;
   wire \fiforeg[0][3] ;
   wire \fiforeg[0][2] ;
   wire \fiforeg[0][1] ;
   wire \fiforeg[0][0] ;
   wire \fiforeg[1][7] ;
   wire \fiforeg[1][6] ;
   wire \fiforeg[1][5] ;
   wire \fiforeg[1][4] ;
   wire \fiforeg[1][3] ;
   wire \fiforeg[1][2] ;
   wire \fiforeg[1][1] ;
   wire \fiforeg[1][0] ;
   wire \fiforeg[2][7] ;
   wire \fiforeg[2][6] ;
   wire \fiforeg[2][5] ;
   wire \fiforeg[2][4] ;
   wire \fiforeg[2][3] ;
   wire \fiforeg[2][2] ;
   wire \fiforeg[2][1] ;
   wire \fiforeg[2][0] ;
   wire \fiforeg[3][7] ;
   wire \fiforeg[3][6] ;
   wire \fiforeg[3][5] ;
   wire \fiforeg[3][4] ;
   wire \fiforeg[3][3] ;
   wire \fiforeg[3][2] ;
   wire \fiforeg[3][1] ;
   wire \fiforeg[3][0] ;
   wire \fiforeg[4][7] ;
   wire \fiforeg[4][6] ;
   wire \fiforeg[4][5] ;
   wire \fiforeg[4][4] ;
   wire \fiforeg[4][3] ;
   wire \fiforeg[4][2] ;
   wire \fiforeg[4][1] ;
   wire \fiforeg[4][0] ;
   wire \fiforeg[5][7] ;
   wire \fiforeg[5][6] ;
   wire \fiforeg[5][5] ;
   wire \fiforeg[5][4] ;
   wire \fiforeg[5][3] ;
   wire \fiforeg[5][2] ;
   wire \fiforeg[5][1] ;
   wire \fiforeg[5][0] ;
   wire \fiforeg[6][7] ;
   wire \fiforeg[6][6] ;
   wire \fiforeg[6][5] ;
   wire \fiforeg[6][4] ;
   wire \fiforeg[6][3] ;
   wire \fiforeg[6][2] ;
   wire \fiforeg[6][1] ;
   wire \fiforeg[6][0] ;
   wire \fiforeg[7][7] ;
   wire \fiforeg[7][6] ;
   wire \fiforeg[7][5] ;
   wire \fiforeg[7][4] ;
   wire \fiforeg[7][3] ;
   wire \fiforeg[7][2] ;
   wire \fiforeg[7][1] ;
   wire \fiforeg[7][0] ;
   wire N17;
   wire N18;
   wire N19;
   wire N20;
   wire N21;
   wire N22;
   wire N23;
   wire N24;
   wire n89;
   wire n90;
   wire n91;
   wire n92;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n97;
   wire n98;
   wire n99;
   wire n100;
   wire n101;
   wire n102;
   wire n103;
   wire n104;
   wire n105;
   wire n106;
   wire n107;
   wire n108;
   wire n109;
   wire n110;
   wire n111;
   wire n112;
   wire n113;
   wire n114;
   wire n115;
   wire n116;
   wire n117;
   wire n118;
   wire n119;
   wire n120;
   wire n121;
   wire n122;
   wire n123;
   wire n124;
   wire n125;
   wire n126;
   wire n127;
   wire n128;
   wire n129;
   wire n130;
   wire n131;
   wire n132;
   wire n133;
   wire n134;
   wire n135;
   wire n136;
   wire n137;
   wire n138;
   wire n139;
   wire n140;
   wire n141;
   wire n142;
   wire n143;
   wire n144;
   wire n145;
   wire n146;
   wire n147;
   wire n148;
   wire n149;
   wire n150;
   wire n151;
   wire n152;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire n73;
   wire n74;
   wire n75;
   wire n76;
   wire n77;
   wire n78;
   wire n79;
   wire n80;
   wire n81;
   wire n82;
   wire n83;
   wire n84;
   wire n85;
   wire n86;
   wire n87;
   wire n88;
   wire n153;
   wire n154;
   wire n155;
   wire n156;
   wire n157;
   wire n158;
   wire n159;
   wire n160;
   wire n161;
   wire n162;
   wire n163;
   wire n164;
   wire n165;
   wire n166;
   wire n167;
   wire n168;
   wire n169;
   wire n170;
   wire n171;
   wire n172;
   wire n173;
   wire n174;
   wire n175;
   wire n176;
   wire n177;
   wire n178;
   wire n179;
   wire n180;
   wire n181;
   wire n182;
   wire n183;
   wire n184;
   wire n185;
   wire n186;
   wire n187;
   wire n188;
   wire n189;
   wire n190;
   wire n191;
   wire n192;
   wire n193;
   wire n194;
   wire n195;
   wire n196;
   wire n197;
   wire n198;
   wire n199;
   wire n200;
   wire n201;
   wire n202;
   wire n203;
   wire n204;
   wire n205;
   wire n206;
   wire n207;
   wire n208;
   wire n209;
   wire n210;
   wire n211;
   wire n212;
   wire n213;
   wire n214;
   wire n215;
   wire n216;
   wire n217;
   wire n218;
   wire n219;
   wire n220;
   wire n221;
   wire n222;
   wire n223;
   wire n224;
   wire n225;
   wire n226;
   wire n227;
   wire n228;
   wire n229;
   wire n230;
   wire n231;
   wire n232;
   wire n233;
   wire n234;
   wire n235;
   wire n236;
   wire n237;
   wire n238;
   wire n239;
   wire n240;
   wire n241;
   wire n242;
   wire n243;
   wire n244;
   wire n245;
   wire n246;
   wire n247;
   wire n248;
   wire n249;
   wire n250;
   wire n251;
   wire n252;
   wire n253;
   wire n254;
   wire n255;
   wire n256;
   wire n257;
   wire n258;
   wire n259;
   wire n260;
   wire n261;
   wire n262;

   assign N11 = raddr[1] ;
   assign N12 = raddr[2] ;
   assign N14 = waddr[1] ;
   assign N15 = waddr[2] ;

   BUFX2 FE_OFC25_n241 (.A(n241),
	.Y(FE_OFN25_n241));
   BUFX2 FE_OFC24_n223 (.A(n223),
	.Y(FE_OFN24_n223));
   BUFX2 FE_OFC23_n203 (.A(n203),
	.Y(FE_OFN23_n203));
   BUFX2 FE_OFC22_n183 (.A(n183),
	.Y(FE_OFN22_n183));
   BUFX2 FE_OFC21_n250 (.A(n250),
	.Y(FE_OFN21_n250));
   BUFX2 FE_OFC20_n232 (.A(n232),
	.Y(FE_OFN20_n232));
   BUFX2 FE_OFC19_n214 (.A(n214),
	.Y(FE_OFN19_n214));
   BUFX2 FE_OFC18_n190 (.A(n190),
	.Y(FE_OFN18_n190));
   BUFX2 FE_OFC14_n175 (.A(n175),
	.Y(FE_OFN14_n175));
   BUFX2 FE_OFC13_n174 (.A(n174),
	.Y(FE_OFN13_n174));
   BUFX2 FE_OFC12_n173 (.A(n173),
	.Y(FE_OFN12_n173));
   BUFX2 FE_OFC11_n172 (.A(n172),
	.Y(FE_OFN11_n172));
   BUFX2 FE_OFC10_n56 (.A(n56),
	.Y(FE_OFN10_n56));
   BUFX4 FE_OFC9_n55 (.A(n55),
	.Y(FE_OFN9_n55));
   BUFX2 FE_OFC8_n54 (.A(n54),
	.Y(FE_OFN8_n54));
   BUFX2 FE_OFC7_n53 (.A(n53),
	.Y(FE_OFN7_n53));
   BUFX2 FE_OFC6_raddr_0 (.A(raddr[0]),
	.Y(FE_OFN6_raddr_0));
   BUFX2 FE_OFC5_waddr_0 (.A(waddr[0]),
	.Y(FE_OFN5_waddr_0));
   DFFPOSX1 \fiforeg_reg[0][7]  (.CLK(wclk),
	.D(n152),
	.Q(\fiforeg[0][7] ));
   DFFPOSX1 \fiforeg_reg[0][6]  (.CLK(wclk),
	.D(n151),
	.Q(\fiforeg[0][6] ));
   DFFPOSX1 \fiforeg_reg[0][5]  (.CLK(wclk),
	.D(n150),
	.Q(\fiforeg[0][5] ));
   DFFPOSX1 \fiforeg_reg[0][4]  (.CLK(wclk),
	.D(n149),
	.Q(\fiforeg[0][4] ));
   DFFPOSX1 \fiforeg_reg[0][3]  (.CLK(wclk),
	.D(n148),
	.Q(\fiforeg[0][3] ));
   DFFPOSX1 \fiforeg_reg[0][2]  (.CLK(wclk),
	.D(n147),
	.Q(\fiforeg[0][2] ));
   DFFPOSX1 \fiforeg_reg[0][1]  (.CLK(wclk),
	.D(n146),
	.Q(\fiforeg[0][1] ));
   DFFPOSX1 \fiforeg_reg[0][0]  (.CLK(wclk),
	.D(n145),
	.Q(\fiforeg[0][0] ));
   DFFPOSX1 \fiforeg_reg[1][7]  (.CLK(wclk),
	.D(n144),
	.Q(\fiforeg[1][7] ));
   DFFPOSX1 \fiforeg_reg[1][6]  (.CLK(wclk),
	.D(n143),
	.Q(\fiforeg[1][6] ));
   DFFPOSX1 \fiforeg_reg[1][5]  (.CLK(wclk),
	.D(n142),
	.Q(\fiforeg[1][5] ));
   DFFPOSX1 \fiforeg_reg[1][4]  (.CLK(wclk),
	.D(n141),
	.Q(\fiforeg[1][4] ));
   DFFPOSX1 \fiforeg_reg[1][3]  (.CLK(wclk),
	.D(n140),
	.Q(\fiforeg[1][3] ));
   DFFPOSX1 \fiforeg_reg[1][2]  (.CLK(wclk),
	.D(n139),
	.Q(\fiforeg[1][2] ));
   DFFPOSX1 \fiforeg_reg[1][1]  (.CLK(wclk),
	.D(n138),
	.Q(\fiforeg[1][1] ));
   DFFPOSX1 \fiforeg_reg[1][0]  (.CLK(wclk),
	.D(n137),
	.Q(\fiforeg[1][0] ));
   DFFPOSX1 \fiforeg_reg[2][7]  (.CLK(wclk),
	.D(n136),
	.Q(\fiforeg[2][7] ));
   DFFPOSX1 \fiforeg_reg[2][6]  (.CLK(wclk),
	.D(n135),
	.Q(\fiforeg[2][6] ));
   DFFPOSX1 \fiforeg_reg[2][5]  (.CLK(wclk),
	.D(n134),
	.Q(\fiforeg[2][5] ));
   DFFPOSX1 \fiforeg_reg[2][4]  (.CLK(wclk),
	.D(n133),
	.Q(\fiforeg[2][4] ));
   DFFPOSX1 \fiforeg_reg[2][3]  (.CLK(wclk),
	.D(n132),
	.Q(\fiforeg[2][3] ));
   DFFPOSX1 \fiforeg_reg[2][2]  (.CLK(wclk),
	.D(n131),
	.Q(\fiforeg[2][2] ));
   DFFPOSX1 \fiforeg_reg[2][1]  (.CLK(wclk),
	.D(n130),
	.Q(\fiforeg[2][1] ));
   DFFPOSX1 \fiforeg_reg[2][0]  (.CLK(wclk),
	.D(n129),
	.Q(\fiforeg[2][0] ));
   DFFPOSX1 \fiforeg_reg[3][7]  (.CLK(wclk),
	.D(n128),
	.Q(\fiforeg[3][7] ));
   DFFPOSX1 \fiforeg_reg[3][6]  (.CLK(wclk),
	.D(n127),
	.Q(\fiforeg[3][6] ));
   DFFPOSX1 \fiforeg_reg[3][5]  (.CLK(wclk),
	.D(n126),
	.Q(\fiforeg[3][5] ));
   DFFPOSX1 \fiforeg_reg[3][4]  (.CLK(wclk),
	.D(n125),
	.Q(\fiforeg[3][4] ));
   DFFPOSX1 \fiforeg_reg[3][3]  (.CLK(wclk),
	.D(n124),
	.Q(\fiforeg[3][3] ));
   DFFPOSX1 \fiforeg_reg[3][2]  (.CLK(wclk),
	.D(n123),
	.Q(\fiforeg[3][2] ));
   DFFPOSX1 \fiforeg_reg[3][1]  (.CLK(wclk),
	.D(n122),
	.Q(\fiforeg[3][1] ));
   DFFPOSX1 \fiforeg_reg[3][0]  (.CLK(wclk),
	.D(n121),
	.Q(\fiforeg[3][0] ));
   DFFPOSX1 \fiforeg_reg[4][7]  (.CLK(wclk),
	.D(n120),
	.Q(\fiforeg[4][7] ));
   DFFPOSX1 \fiforeg_reg[4][6]  (.CLK(wclk),
	.D(n119),
	.Q(\fiforeg[4][6] ));
   DFFPOSX1 \fiforeg_reg[4][5]  (.CLK(wclk),
	.D(n118),
	.Q(\fiforeg[4][5] ));
   DFFPOSX1 \fiforeg_reg[4][4]  (.CLK(wclk),
	.D(n117),
	.Q(\fiforeg[4][4] ));
   DFFPOSX1 \fiforeg_reg[4][3]  (.CLK(wclk),
	.D(n116),
	.Q(\fiforeg[4][3] ));
   DFFPOSX1 \fiforeg_reg[4][2]  (.CLK(wclk),
	.D(n115),
	.Q(\fiforeg[4][2] ));
   DFFPOSX1 \fiforeg_reg[4][1]  (.CLK(wclk),
	.D(n114),
	.Q(\fiforeg[4][1] ));
   DFFPOSX1 \fiforeg_reg[4][0]  (.CLK(wclk),
	.D(n113),
	.Q(\fiforeg[4][0] ));
   DFFPOSX1 \fiforeg_reg[5][7]  (.CLK(wclk),
	.D(n112),
	.Q(\fiforeg[5][7] ));
   DFFPOSX1 \fiforeg_reg[5][6]  (.CLK(wclk),
	.D(n111),
	.Q(\fiforeg[5][6] ));
   DFFPOSX1 \fiforeg_reg[5][5]  (.CLK(wclk),
	.D(n110),
	.Q(\fiforeg[5][5] ));
   DFFPOSX1 \fiforeg_reg[5][4]  (.CLK(wclk),
	.D(n109),
	.Q(\fiforeg[5][4] ));
   DFFPOSX1 \fiforeg_reg[5][3]  (.CLK(wclk),
	.D(n108),
	.Q(\fiforeg[5][3] ));
   DFFPOSX1 \fiforeg_reg[5][2]  (.CLK(wclk),
	.D(n107),
	.Q(\fiforeg[5][2] ));
   DFFPOSX1 \fiforeg_reg[5][1]  (.CLK(wclk),
	.D(n106),
	.Q(\fiforeg[5][1] ));
   DFFPOSX1 \fiforeg_reg[5][0]  (.CLK(wclk),
	.D(n105),
	.Q(\fiforeg[5][0] ));
   DFFPOSX1 \fiforeg_reg[6][7]  (.CLK(wclk),
	.D(n104),
	.Q(\fiforeg[6][7] ));
   DFFPOSX1 \fiforeg_reg[6][6]  (.CLK(wclk),
	.D(n103),
	.Q(\fiforeg[6][6] ));
   DFFPOSX1 \fiforeg_reg[6][5]  (.CLK(wclk),
	.D(n102),
	.Q(\fiforeg[6][5] ));
   DFFPOSX1 \fiforeg_reg[6][4]  (.CLK(wclk),
	.D(n101),
	.Q(\fiforeg[6][4] ));
   DFFPOSX1 \fiforeg_reg[6][3]  (.CLK(wclk),
	.D(n100),
	.Q(\fiforeg[6][3] ));
   DFFPOSX1 \fiforeg_reg[6][2]  (.CLK(wclk),
	.D(n99),
	.Q(\fiforeg[6][2] ));
   DFFPOSX1 \fiforeg_reg[6][1]  (.CLK(wclk),
	.D(n98),
	.Q(\fiforeg[6][1] ));
   DFFPOSX1 \fiforeg_reg[6][0]  (.CLK(wclk),
	.D(n97),
	.Q(\fiforeg[6][0] ));
   DFFPOSX1 \fiforeg_reg[7][7]  (.CLK(wclk),
	.D(n96),
	.Q(\fiforeg[7][7] ));
   DFFPOSX1 \fiforeg_reg[7][6]  (.CLK(wclk),
	.D(n95),
	.Q(\fiforeg[7][6] ));
   DFFPOSX1 \fiforeg_reg[7][5]  (.CLK(wclk),
	.D(n94),
	.Q(\fiforeg[7][5] ));
   DFFPOSX1 \fiforeg_reg[7][4]  (.CLK(wclk),
	.D(n93),
	.Q(\fiforeg[7][4] ));
   DFFPOSX1 \fiforeg_reg[7][3]  (.CLK(wclk),
	.D(n92),
	.Q(\fiforeg[7][3] ));
   DFFPOSX1 \fiforeg_reg[7][2]  (.CLK(wclk),
	.D(n91),
	.Q(\fiforeg[7][2] ));
   DFFPOSX1 \fiforeg_reg[7][1]  (.CLK(wclk),
	.D(n90),
	.Q(\fiforeg[7][1] ));
   DFFPOSX1 \fiforeg_reg[7][0]  (.CLK(wclk),
	.D(n89),
	.Q(\fiforeg[7][0] ));
   NOR2X1 U10 (.A(n63),
	.B(N11),
	.Y(n54));
   NOR2X1 U11 (.A(n63),
	.B(n62),
	.Y(n53));
   AOI22X1 U12 (.A(\fiforeg[4][0] ),
	.B(FE_OFN8_n54),
	.C(\fiforeg[6][0] ),
	.D(FE_OFN7_n53),
	.Y(n10));
   NOR2X1 U13 (.A(N11),
	.B(N12),
	.Y(n56));
   NOR2X1 U14 (.A(n62),
	.B(N12),
	.Y(n55));
   AOI22X1 U15 (.A(\fiforeg[0][0] ),
	.B(FE_OFN10_n56),
	.C(\fiforeg[2][0] ),
	.D(FE_OFN9_n55),
	.Y(n9));
   AOI21X1 U16 (.A(n10),
	.B(n9),
	.C(FE_OFN6_raddr_0),
	.Y(n14));
   AOI22X1 U17 (.A(\fiforeg[5][0] ),
	.B(FE_OFN8_n54),
	.C(\fiforeg[7][0] ),
	.D(FE_OFN7_n53),
	.Y(n12));
   AOI22X1 U18 (.A(\fiforeg[1][0] ),
	.B(FE_OFN10_n56),
	.C(\fiforeg[3][0] ),
	.D(FE_OFN9_n55),
	.Y(n11));
   AOI21X1 U19 (.A(n12),
	.B(n11),
	.C(n61),
	.Y(n13));
   OR2X1 U20 (.A(n14),
	.B(n13),
	.Y(rdata[0]));
   AOI22X1 U21 (.A(\fiforeg[4][1] ),
	.B(FE_OFN8_n54),
	.C(\fiforeg[6][1] ),
	.D(FE_OFN7_n53),
	.Y(n16));
   AOI22X1 U22 (.A(\fiforeg[0][1] ),
	.B(FE_OFN10_n56),
	.C(\fiforeg[2][1] ),
	.D(FE_OFN9_n55),
	.Y(n15));
   AOI21X1 U23 (.A(n16),
	.B(n15),
	.C(FE_OFN6_raddr_0),
	.Y(n20));
   AOI22X1 U24 (.A(\fiforeg[5][1] ),
	.B(FE_OFN8_n54),
	.C(\fiforeg[7][1] ),
	.D(FE_OFN7_n53),
	.Y(n18));
   AOI22X1 U25 (.A(\fiforeg[1][1] ),
	.B(FE_OFN10_n56),
	.C(\fiforeg[3][1] ),
	.D(FE_OFN9_n55),
	.Y(n17));
   AOI21X1 U26 (.A(n18),
	.B(n17),
	.C(n61),
	.Y(n19));
   OR2X1 U27 (.A(n20),
	.B(n19),
	.Y(rdata[1]));
   AOI22X1 U28 (.A(\fiforeg[4][2] ),
	.B(FE_OFN8_n54),
	.C(\fiforeg[6][2] ),
	.D(FE_OFN7_n53),
	.Y(n22));
   AOI22X1 U29 (.A(\fiforeg[0][2] ),
	.B(FE_OFN10_n56),
	.C(\fiforeg[2][2] ),
	.D(FE_OFN9_n55),
	.Y(n21));
   AOI21X1 U30 (.A(n22),
	.B(n21),
	.C(FE_OFN6_raddr_0),
	.Y(n26));
   AOI22X1 U31 (.A(\fiforeg[5][2] ),
	.B(FE_OFN8_n54),
	.C(\fiforeg[7][2] ),
	.D(FE_OFN7_n53),
	.Y(n24));
   AOI22X1 U32 (.A(\fiforeg[1][2] ),
	.B(FE_OFN10_n56),
	.C(\fiforeg[3][2] ),
	.D(FE_OFN9_n55),
	.Y(n23));
   AOI21X1 U33 (.A(n24),
	.B(n23),
	.C(n61),
	.Y(n25));
   OR2X1 U34 (.A(n26),
	.B(n25),
	.Y(rdata[2]));
   AOI22X1 U35 (.A(\fiforeg[4][3] ),
	.B(FE_OFN8_n54),
	.C(\fiforeg[6][3] ),
	.D(FE_OFN7_n53),
	.Y(n28));
   AOI22X1 U36 (.A(\fiforeg[0][3] ),
	.B(FE_OFN10_n56),
	.C(\fiforeg[2][3] ),
	.D(FE_OFN9_n55),
	.Y(n27));
   AOI21X1 U37 (.A(n28),
	.B(n27),
	.C(FE_OFN6_raddr_0),
	.Y(n32));
   AOI22X1 U38 (.A(\fiforeg[5][3] ),
	.B(FE_OFN8_n54),
	.C(\fiforeg[7][3] ),
	.D(FE_OFN7_n53),
	.Y(n30));
   AOI22X1 U39 (.A(\fiforeg[1][3] ),
	.B(FE_OFN10_n56),
	.C(\fiforeg[3][3] ),
	.D(FE_OFN9_n55),
	.Y(n29));
   AOI21X1 U40 (.A(n30),
	.B(n29),
	.C(n61),
	.Y(n31));
   OR2X1 U41 (.A(n32),
	.B(n31),
	.Y(rdata[3]));
   AOI22X1 U42 (.A(\fiforeg[4][4] ),
	.B(FE_OFN8_n54),
	.C(\fiforeg[6][4] ),
	.D(FE_OFN7_n53),
	.Y(n34));
   AOI22X1 U43 (.A(\fiforeg[0][4] ),
	.B(FE_OFN10_n56),
	.C(\fiforeg[2][4] ),
	.D(FE_OFN9_n55),
	.Y(n33));
   AOI21X1 U44 (.A(n34),
	.B(n33),
	.C(FE_OFN6_raddr_0),
	.Y(n38));
   AOI22X1 U45 (.A(\fiforeg[5][4] ),
	.B(FE_OFN8_n54),
	.C(\fiforeg[7][4] ),
	.D(FE_OFN7_n53),
	.Y(n36));
   AOI22X1 U46 (.A(\fiforeg[1][4] ),
	.B(FE_OFN10_n56),
	.C(\fiforeg[3][4] ),
	.D(FE_OFN9_n55),
	.Y(n35));
   AOI21X1 U47 (.A(n36),
	.B(n35),
	.C(n61),
	.Y(n37));
   OR2X1 U48 (.A(n38),
	.B(n37),
	.Y(rdata[4]));
   AOI22X1 U49 (.A(\fiforeg[4][5] ),
	.B(n54),
	.C(\fiforeg[6][5] ),
	.D(FE_OFN7_n53),
	.Y(n40));
   AOI22X1 U50 (.A(\fiforeg[0][5] ),
	.B(n56),
	.C(\fiforeg[2][5] ),
	.D(FE_OFN9_n55),
	.Y(n39));
   AOI21X1 U51 (.A(n40),
	.B(n39),
	.C(FE_OFN6_raddr_0),
	.Y(n44));
   AOI22X1 U52 (.A(\fiforeg[5][5] ),
	.B(n54),
	.C(\fiforeg[7][5] ),
	.D(FE_OFN7_n53),
	.Y(n42));
   AOI22X1 U53 (.A(\fiforeg[1][5] ),
	.B(n56),
	.C(\fiforeg[3][5] ),
	.D(FE_OFN9_n55),
	.Y(n41));
   AOI21X1 U54 (.A(n42),
	.B(n41),
	.C(n61),
	.Y(n43));
   OR2X1 U55 (.A(n44),
	.B(n43),
	.Y(rdata[5]));
   AOI22X1 U56 (.A(\fiforeg[4][6] ),
	.B(n54),
	.C(\fiforeg[6][6] ),
	.D(FE_OFN7_n53),
	.Y(n46));
   AOI22X1 U57 (.A(\fiforeg[0][6] ),
	.B(n56),
	.C(\fiforeg[2][6] ),
	.D(FE_OFN9_n55),
	.Y(n45));
   AOI21X1 U58 (.A(n46),
	.B(n45),
	.C(FE_OFN6_raddr_0),
	.Y(n50));
   AOI22X1 U59 (.A(\fiforeg[5][6] ),
	.B(n54),
	.C(\fiforeg[7][6] ),
	.D(FE_OFN7_n53),
	.Y(n48));
   AOI22X1 U60 (.A(\fiforeg[1][6] ),
	.B(n56),
	.C(\fiforeg[3][6] ),
	.D(FE_OFN9_n55),
	.Y(n47));
   AOI21X1 U61 (.A(n48),
	.B(n47),
	.C(n61),
	.Y(n49));
   OR2X1 U62 (.A(n50),
	.B(n49),
	.Y(rdata[6]));
   AOI22X1 U63 (.A(\fiforeg[4][7] ),
	.B(n54),
	.C(\fiforeg[6][7] ),
	.D(n53),
	.Y(n52));
   AOI22X1 U64 (.A(\fiforeg[0][7] ),
	.B(n56),
	.C(\fiforeg[2][7] ),
	.D(FE_OFN9_n55),
	.Y(n51));
   AOI21X1 U65 (.A(n52),
	.B(n51),
	.C(FE_OFN6_raddr_0),
	.Y(n60));
   AOI22X1 U66 (.A(\fiforeg[5][7] ),
	.B(FE_OFN8_n54),
	.C(\fiforeg[7][7] ),
	.D(n53),
	.Y(n58));
   AOI22X1 U67 (.A(\fiforeg[1][7] ),
	.B(FE_OFN10_n56),
	.C(\fiforeg[3][7] ),
	.D(FE_OFN9_n55),
	.Y(n57));
   AOI21X1 U68 (.A(n58),
	.B(n57),
	.C(n61),
	.Y(n59));
   OR2X1 U69 (.A(n60),
	.B(n59),
	.Y(rdata[7]));
   INVX2 U70 (.A(FE_OFN6_raddr_0),
	.Y(n61));
   INVX2 U71 (.A(N11),
	.Y(n62));
   INVX2 U72 (.A(N12),
	.Y(n63));
   NOR2X1 U73 (.A(n211),
	.B(N14),
	.Y(n173));
   NOR2X1 U74 (.A(n211),
	.B(n180),
	.Y(n172));
   AOI22X1 U75 (.A(\fiforeg[4][0] ),
	.B(FE_OFN12_n173),
	.C(\fiforeg[6][0] ),
	.D(FE_OFN11_n172),
	.Y(n65));
   NOR2X1 U76 (.A(N14),
	.B(N15),
	.Y(n175));
   NOR2X1 U77 (.A(n180),
	.B(N15),
	.Y(n174));
   AOI22X1 U78 (.A(\fiforeg[0][0] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[2][0] ),
	.D(FE_OFN13_n174),
	.Y(n64));
   AOI21X1 U79 (.A(n65),
	.B(n64),
	.C(FE_OFN5_waddr_0),
	.Y(n69));
   AOI22X1 U80 (.A(\fiforeg[5][0] ),
	.B(FE_OFN12_n173),
	.C(\fiforeg[7][0] ),
	.D(FE_OFN11_n172),
	.Y(n67));
   AOI22X1 U81 (.A(\fiforeg[1][0] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[3][0] ),
	.D(FE_OFN13_n174),
	.Y(n66));
   AOI21X1 U82 (.A(n67),
	.B(n66),
	.C(n212),
	.Y(n68));
   OR2X1 U83 (.A(n69),
	.B(n68),
	.Y(N24));
   AOI22X1 U84 (.A(FE_OFN12_n173),
	.B(\fiforeg[4][1] ),
	.C(FE_OFN11_n172),
	.D(\fiforeg[6][1] ),
	.Y(n71));
   AOI22X1 U85 (.A(\fiforeg[0][1] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[2][1] ),
	.D(FE_OFN13_n174),
	.Y(n70));
   AOI21X1 U86 (.A(n71),
	.B(n70),
	.C(FE_OFN5_waddr_0),
	.Y(n75));
   AOI22X1 U87 (.A(FE_OFN12_n173),
	.B(\fiforeg[5][1] ),
	.C(\fiforeg[7][1] ),
	.D(FE_OFN11_n172),
	.Y(n73));
   AOI22X1 U88 (.A(\fiforeg[1][1] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[3][1] ),
	.D(FE_OFN13_n174),
	.Y(n72));
   AOI21X1 U89 (.A(n73),
	.B(n72),
	.C(n212),
	.Y(n74));
   OR2X1 U90 (.A(n75),
	.B(n74),
	.Y(N23));
   AOI22X1 U91 (.A(FE_OFN12_n173),
	.B(\fiforeg[4][2] ),
	.C(\fiforeg[6][2] ),
	.D(FE_OFN11_n172),
	.Y(n77));
   AOI22X1 U92 (.A(\fiforeg[0][2] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[2][2] ),
	.D(FE_OFN13_n174),
	.Y(n76));
   AOI21X1 U93 (.A(n76),
	.B(n77),
	.C(FE_OFN5_waddr_0),
	.Y(n81));
   AOI22X1 U94 (.A(FE_OFN12_n173),
	.B(\fiforeg[5][2] ),
	.C(\fiforeg[7][2] ),
	.D(FE_OFN11_n172),
	.Y(n79));
   AOI22X1 U95 (.A(\fiforeg[1][2] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[3][2] ),
	.D(FE_OFN13_n174),
	.Y(n78));
   AOI21X1 U96 (.A(n78),
	.B(n79),
	.C(n212),
	.Y(n80));
   OR2X1 U97 (.A(n81),
	.B(n80),
	.Y(N22));
   AOI22X1 U98 (.A(\fiforeg[4][3] ),
	.B(FE_OFN12_n173),
	.C(\fiforeg[6][3] ),
	.D(FE_OFN11_n172),
	.Y(n83));
   AOI22X1 U99 (.A(\fiforeg[0][3] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[2][3] ),
	.D(FE_OFN13_n174),
	.Y(n82));
   AOI21X1 U100 (.A(n83),
	.B(n82),
	.C(FE_OFN5_waddr_0),
	.Y(n87));
   AOI22X1 U101 (.A(\fiforeg[5][3] ),
	.B(FE_OFN12_n173),
	.C(\fiforeg[7][3] ),
	.D(FE_OFN11_n172),
	.Y(n85));
   AOI22X1 U102 (.A(\fiforeg[1][3] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[3][3] ),
	.D(FE_OFN13_n174),
	.Y(n84));
   AOI21X1 U103 (.A(n85),
	.B(n84),
	.C(n212),
	.Y(n86));
   OR2X1 U104 (.A(n87),
	.B(n86),
	.Y(N21));
   AOI22X1 U105 (.A(\fiforeg[4][4] ),
	.B(FE_OFN12_n173),
	.C(\fiforeg[6][4] ),
	.D(FE_OFN11_n172),
	.Y(n153));
   AOI22X1 U106 (.A(\fiforeg[0][4] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[2][4] ),
	.D(FE_OFN13_n174),
	.Y(n88));
   AOI21X1 U107 (.A(n153),
	.B(n88),
	.C(FE_OFN5_waddr_0),
	.Y(n157));
   AOI22X1 U108 (.A(\fiforeg[5][4] ),
	.B(FE_OFN12_n173),
	.C(\fiforeg[7][4] ),
	.D(FE_OFN11_n172),
	.Y(n155));
   AOI22X1 U109 (.A(\fiforeg[1][4] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[3][4] ),
	.D(FE_OFN13_n174),
	.Y(n154));
   AOI21X1 U110 (.A(n155),
	.B(n154),
	.C(n212),
	.Y(n156));
   OR2X1 U111 (.A(n157),
	.B(n156),
	.Y(N20));
   AOI22X1 U112 (.A(\fiforeg[4][5] ),
	.B(n173),
	.C(\fiforeg[6][5] ),
	.D(n172),
	.Y(n159));
   AOI22X1 U113 (.A(\fiforeg[0][5] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[2][5] ),
	.D(FE_OFN13_n174),
	.Y(n158));
   AOI21X1 U114 (.A(n159),
	.B(n158),
	.C(FE_OFN5_waddr_0),
	.Y(n163));
   AOI22X1 U115 (.A(\fiforeg[5][5] ),
	.B(n173),
	.C(\fiforeg[7][5] ),
	.D(n172),
	.Y(n161));
   AOI22X1 U116 (.A(\fiforeg[1][5] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[3][5] ),
	.D(FE_OFN13_n174),
	.Y(n160));
   AOI21X1 U117 (.A(n161),
	.B(n160),
	.C(n212),
	.Y(n162));
   OR2X1 U118 (.A(n163),
	.B(n162),
	.Y(N19));
   AOI22X1 U119 (.A(\fiforeg[4][6] ),
	.B(n173),
	.C(\fiforeg[6][6] ),
	.D(n172),
	.Y(n165));
   AOI22X1 U120 (.A(\fiforeg[0][6] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[2][6] ),
	.D(FE_OFN13_n174),
	.Y(n164));
   AOI21X1 U121 (.A(n165),
	.B(n164),
	.C(FE_OFN5_waddr_0),
	.Y(n169));
   AOI22X1 U122 (.A(\fiforeg[5][6] ),
	.B(n173),
	.C(\fiforeg[7][6] ),
	.D(n172),
	.Y(n167));
   AOI22X1 U123 (.A(\fiforeg[1][6] ),
	.B(FE_OFN14_n175),
	.C(\fiforeg[3][6] ),
	.D(FE_OFN13_n174),
	.Y(n166));
   AOI21X1 U124 (.A(n167),
	.B(n166),
	.C(n212),
	.Y(n168));
   OR2X1 U125 (.A(n169),
	.B(n168),
	.Y(N18));
   AOI22X1 U126 (.A(\fiforeg[4][7] ),
	.B(FE_OFN12_n173),
	.C(\fiforeg[6][7] ),
	.D(FE_OFN11_n172),
	.Y(n171));
   AOI22X1 U127 (.A(\fiforeg[0][7] ),
	.B(n175),
	.C(\fiforeg[2][7] ),
	.D(n174),
	.Y(n170));
   AOI21X1 U128 (.A(n171),
	.B(n170),
	.C(FE_OFN5_waddr_0),
	.Y(n179));
   AOI22X1 U129 (.A(\fiforeg[5][7] ),
	.B(FE_OFN12_n173),
	.C(\fiforeg[7][7] ),
	.D(FE_OFN11_n172),
	.Y(n177));
   AOI22X1 U130 (.A(\fiforeg[1][7] ),
	.B(n175),
	.C(\fiforeg[3][7] ),
	.D(n174),
	.Y(n176));
   AOI21X1 U131 (.A(n177),
	.B(n176),
	.C(n212),
	.Y(n178));
   OR2X1 U132 (.A(n179),
	.B(n178),
	.Y(N17));
   INVX2 U133 (.A(N14),
	.Y(n180));
   MUX2X1 U134 (.A(n182),
	.B(n181),
	.S(FE_OFN22_n183),
	.Y(n99));
   INVX1 U135 (.A(\fiforeg[6][2] ),
	.Y(n182));
   MUX2X1 U136 (.A(n185),
	.B(n184),
	.S(FE_OFN22_n183),
	.Y(n98));
   INVX1 U137 (.A(\fiforeg[6][1] ),
	.Y(n185));
   MUX2X1 U138 (.A(n187),
	.B(n186),
	.S(FE_OFN22_n183),
	.Y(n97));
   INVX1 U139 (.A(\fiforeg[6][0] ),
	.Y(n187));
   MUX2X1 U140 (.A(n189),
	.B(n188),
	.S(FE_OFN18_n190),
	.Y(n96));
   INVX1 U141 (.A(\fiforeg[7][7] ),
	.Y(n189));
   MUX2X1 U142 (.A(n192),
	.B(n191),
	.S(FE_OFN18_n190),
	.Y(n95));
   INVX1 U143 (.A(\fiforeg[7][6] ),
	.Y(n192));
   MUX2X1 U144 (.A(n194),
	.B(n193),
	.S(FE_OFN18_n190),
	.Y(n94));
   INVX1 U145 (.A(\fiforeg[7][5] ),
	.Y(n194));
   MUX2X1 U146 (.A(n196),
	.B(n195),
	.S(FE_OFN18_n190),
	.Y(n93));
   INVX1 U147 (.A(\fiforeg[7][4] ),
	.Y(n196));
   MUX2X1 U148 (.A(n198),
	.B(n197),
	.S(FE_OFN18_n190),
	.Y(n92));
   INVX1 U149 (.A(\fiforeg[7][3] ),
	.Y(n198));
   MUX2X1 U150 (.A(n199),
	.B(n181),
	.S(FE_OFN18_n190),
	.Y(n91));
   INVX1 U151 (.A(\fiforeg[7][2] ),
	.Y(n199));
   MUX2X1 U152 (.A(n200),
	.B(n184),
	.S(FE_OFN18_n190),
	.Y(n90));
   INVX1 U153 (.A(\fiforeg[7][1] ),
	.Y(n200));
   MUX2X1 U154 (.A(n201),
	.B(n186),
	.S(FE_OFN18_n190),
	.Y(n89));
   NAND3X1 U155 (.A(N15),
	.B(N14),
	.C(FE_OFN5_waddr_0),
	.Y(n190));
   INVX1 U156 (.A(\fiforeg[7][0] ),
	.Y(n201));
   MUX2X1 U157 (.A(n202),
	.B(n188),
	.S(FE_OFN23_n203),
	.Y(n152));
   INVX1 U158 (.A(\fiforeg[0][7] ),
	.Y(n202));
   MUX2X1 U159 (.A(n204),
	.B(n191),
	.S(FE_OFN23_n203),
	.Y(n151));
   INVX1 U160 (.A(\fiforeg[0][6] ),
	.Y(n204));
   MUX2X1 U161 (.A(n205),
	.B(n193),
	.S(FE_OFN23_n203),
	.Y(n150));
   INVX1 U162 (.A(\fiforeg[0][5] ),
	.Y(n205));
   MUX2X1 U163 (.A(n206),
	.B(n195),
	.S(FE_OFN23_n203),
	.Y(n149));
   INVX1 U164 (.A(\fiforeg[0][4] ),
	.Y(n206));
   MUX2X1 U165 (.A(n207),
	.B(n197),
	.S(FE_OFN23_n203),
	.Y(n148));
   INVX1 U166 (.A(\fiforeg[0][3] ),
	.Y(n207));
   MUX2X1 U167 (.A(n208),
	.B(n181),
	.S(FE_OFN23_n203),
	.Y(n147));
   INVX1 U168 (.A(\fiforeg[0][2] ),
	.Y(n208));
   MUX2X1 U169 (.A(n209),
	.B(n184),
	.S(FE_OFN23_n203),
	.Y(n146));
   INVX1 U170 (.A(\fiforeg[0][1] ),
	.Y(n209));
   MUX2X1 U171 (.A(n210),
	.B(n186),
	.S(FE_OFN23_n203),
	.Y(n145));
   NAND3X1 U172 (.A(n180),
	.B(n211),
	.C(n212),
	.Y(n203));
   INVX1 U173 (.A(\fiforeg[0][0] ),
	.Y(n210));
   MUX2X1 U174 (.A(n213),
	.B(n188),
	.S(FE_OFN19_n214),
	.Y(n144));
   INVX1 U175 (.A(\fiforeg[1][7] ),
	.Y(n213));
   MUX2X1 U176 (.A(n215),
	.B(n191),
	.S(FE_OFN19_n214),
	.Y(n143));
   INVX1 U177 (.A(\fiforeg[1][6] ),
	.Y(n215));
   MUX2X1 U178 (.A(n216),
	.B(n193),
	.S(FE_OFN19_n214),
	.Y(n142));
   INVX1 U179 (.A(\fiforeg[1][5] ),
	.Y(n216));
   MUX2X1 U180 (.A(n217),
	.B(n195),
	.S(FE_OFN19_n214),
	.Y(n141));
   INVX1 U181 (.A(\fiforeg[1][4] ),
	.Y(n217));
   MUX2X1 U182 (.A(n218),
	.B(n197),
	.S(FE_OFN19_n214),
	.Y(n140));
   INVX1 U183 (.A(\fiforeg[1][3] ),
	.Y(n218));
   MUX2X1 U184 (.A(n219),
	.B(n181),
	.S(FE_OFN19_n214),
	.Y(n139));
   INVX1 U185 (.A(\fiforeg[1][2] ),
	.Y(n219));
   MUX2X1 U186 (.A(n220),
	.B(n184),
	.S(FE_OFN19_n214),
	.Y(n138));
   INVX1 U187 (.A(\fiforeg[1][1] ),
	.Y(n220));
   MUX2X1 U188 (.A(n221),
	.B(n186),
	.S(FE_OFN19_n214),
	.Y(n137));
   NAND3X1 U189 (.A(n180),
	.B(n211),
	.C(FE_OFN5_waddr_0),
	.Y(n214));
   INVX1 U190 (.A(\fiforeg[1][0] ),
	.Y(n221));
   MUX2X1 U191 (.A(n222),
	.B(n188),
	.S(FE_OFN24_n223),
	.Y(n136));
   INVX1 U192 (.A(\fiforeg[2][7] ),
	.Y(n222));
   MUX2X1 U193 (.A(n224),
	.B(n191),
	.S(FE_OFN24_n223),
	.Y(n135));
   INVX1 U194 (.A(\fiforeg[2][6] ),
	.Y(n224));
   MUX2X1 U195 (.A(n225),
	.B(n193),
	.S(FE_OFN24_n223),
	.Y(n134));
   INVX1 U196 (.A(\fiforeg[2][5] ),
	.Y(n225));
   MUX2X1 U197 (.A(n226),
	.B(n195),
	.S(FE_OFN24_n223),
	.Y(n133));
   INVX1 U198 (.A(\fiforeg[2][4] ),
	.Y(n226));
   MUX2X1 U199 (.A(n227),
	.B(n197),
	.S(FE_OFN24_n223),
	.Y(n132));
   INVX1 U200 (.A(\fiforeg[2][3] ),
	.Y(n227));
   MUX2X1 U201 (.A(n228),
	.B(n181),
	.S(FE_OFN24_n223),
	.Y(n131));
   INVX1 U202 (.A(\fiforeg[2][2] ),
	.Y(n228));
   MUX2X1 U203 (.A(n229),
	.B(n184),
	.S(FE_OFN24_n223),
	.Y(n130));
   INVX1 U204 (.A(\fiforeg[2][1] ),
	.Y(n229));
   MUX2X1 U205 (.A(n230),
	.B(n186),
	.S(FE_OFN24_n223),
	.Y(n129));
   NAND3X1 U206 (.A(n212),
	.B(n211),
	.C(N14),
	.Y(n223));
   INVX1 U207 (.A(\fiforeg[2][0] ),
	.Y(n230));
   MUX2X1 U208 (.A(n231),
	.B(n188),
	.S(FE_OFN20_n232),
	.Y(n128));
   INVX1 U209 (.A(\fiforeg[3][7] ),
	.Y(n231));
   MUX2X1 U210 (.A(n233),
	.B(n191),
	.S(FE_OFN20_n232),
	.Y(n127));
   INVX1 U211 (.A(\fiforeg[3][6] ),
	.Y(n233));
   MUX2X1 U212 (.A(n234),
	.B(n193),
	.S(FE_OFN20_n232),
	.Y(n126));
   INVX1 U213 (.A(\fiforeg[3][5] ),
	.Y(n234));
   MUX2X1 U214 (.A(n235),
	.B(n195),
	.S(FE_OFN20_n232),
	.Y(n125));
   INVX1 U215 (.A(\fiforeg[3][4] ),
	.Y(n235));
   MUX2X1 U216 (.A(n236),
	.B(n197),
	.S(FE_OFN20_n232),
	.Y(n124));
   INVX1 U217 (.A(\fiforeg[3][3] ),
	.Y(n236));
   MUX2X1 U218 (.A(n237),
	.B(n181),
	.S(FE_OFN20_n232),
	.Y(n123));
   INVX1 U219 (.A(\fiforeg[3][2] ),
	.Y(n237));
   MUX2X1 U220 (.A(n238),
	.B(n184),
	.S(FE_OFN20_n232),
	.Y(n122));
   INVX1 U221 (.A(\fiforeg[3][1] ),
	.Y(n238));
   MUX2X1 U222 (.A(n239),
	.B(n186),
	.S(FE_OFN20_n232),
	.Y(n121));
   NAND3X1 U223 (.A(N14),
	.B(n211),
	.C(FE_OFN5_waddr_0),
	.Y(n232));
   INVX2 U224 (.A(N15),
	.Y(n211));
   INVX1 U225 (.A(\fiforeg[3][0] ),
	.Y(n239));
   MUX2X1 U226 (.A(n240),
	.B(n188),
	.S(FE_OFN25_n241),
	.Y(n120));
   INVX1 U227 (.A(\fiforeg[4][7] ),
	.Y(n240));
   MUX2X1 U228 (.A(n242),
	.B(n191),
	.S(FE_OFN25_n241),
	.Y(n119));
   INVX1 U229 (.A(\fiforeg[4][6] ),
	.Y(n242));
   MUX2X1 U230 (.A(n243),
	.B(n193),
	.S(FE_OFN25_n241),
	.Y(n118));
   INVX1 U231 (.A(\fiforeg[4][5] ),
	.Y(n243));
   MUX2X1 U232 (.A(n244),
	.B(n195),
	.S(FE_OFN25_n241),
	.Y(n117));
   INVX1 U233 (.A(\fiforeg[4][4] ),
	.Y(n244));
   MUX2X1 U234 (.A(n245),
	.B(n197),
	.S(FE_OFN25_n241),
	.Y(n116));
   INVX1 U235 (.A(\fiforeg[4][3] ),
	.Y(n245));
   MUX2X1 U236 (.A(n246),
	.B(n181),
	.S(FE_OFN25_n241),
	.Y(n115));
   INVX1 U237 (.A(\fiforeg[4][2] ),
	.Y(n246));
   MUX2X1 U238 (.A(n247),
	.B(n184),
	.S(FE_OFN25_n241),
	.Y(n114));
   INVX1 U239 (.A(\fiforeg[4][1] ),
	.Y(n247));
   MUX2X1 U240 (.A(n248),
	.B(n186),
	.S(FE_OFN25_n241),
	.Y(n113));
   NAND3X1 U241 (.A(n212),
	.B(n180),
	.C(N15),
	.Y(n241));
   INVX1 U242 (.A(\fiforeg[4][0] ),
	.Y(n248));
   MUX2X1 U243 (.A(n249),
	.B(n188),
	.S(FE_OFN21_n250),
	.Y(n112));
   INVX1 U244 (.A(\fiforeg[5][7] ),
	.Y(n249));
   MUX2X1 U245 (.A(n251),
	.B(n191),
	.S(FE_OFN21_n250),
	.Y(n111));
   INVX1 U246 (.A(\fiforeg[5][6] ),
	.Y(n251));
   MUX2X1 U247 (.A(n252),
	.B(n193),
	.S(FE_OFN21_n250),
	.Y(n110));
   INVX1 U248 (.A(\fiforeg[5][5] ),
	.Y(n252));
   MUX2X1 U249 (.A(n253),
	.B(n195),
	.S(FE_OFN21_n250),
	.Y(n109));
   INVX1 U250 (.A(\fiforeg[5][4] ),
	.Y(n253));
   MUX2X1 U251 (.A(n254),
	.B(n197),
	.S(FE_OFN21_n250),
	.Y(n108));
   INVX1 U252 (.A(\fiforeg[5][3] ),
	.Y(n254));
   MUX2X1 U253 (.A(n255),
	.B(n181),
	.S(FE_OFN21_n250),
	.Y(n107));
   INVX1 U254 (.A(\fiforeg[5][2] ),
	.Y(n255));
   MUX2X1 U255 (.A(wdata[2]),
	.B(N22),
	.S(wenable),
	.Y(n181));
   MUX2X1 U256 (.A(n256),
	.B(n184),
	.S(FE_OFN21_n250),
	.Y(n106));
   INVX1 U257 (.A(\fiforeg[5][1] ),
	.Y(n256));
   MUX2X1 U258 (.A(wdata[1]),
	.B(N23),
	.S(wenable),
	.Y(n184));
   MUX2X1 U259 (.A(n257),
	.B(n186),
	.S(FE_OFN21_n250),
	.Y(n105));
   NAND3X1 U260 (.A(N15),
	.B(n180),
	.C(FE_OFN5_waddr_0),
	.Y(n250));
   INVX1 U261 (.A(\fiforeg[5][0] ),
	.Y(n257));
   MUX2X1 U262 (.A(wdata[0]),
	.B(N24),
	.S(wenable),
	.Y(n186));
   MUX2X1 U263 (.A(n258),
	.B(n188),
	.S(FE_OFN22_n183),
	.Y(n104));
   INVX1 U264 (.A(\fiforeg[6][7] ),
	.Y(n258));
   MUX2X1 U265 (.A(wdata[7]),
	.B(N17),
	.S(wenable),
	.Y(n188));
   MUX2X1 U266 (.A(n259),
	.B(n191),
	.S(FE_OFN22_n183),
	.Y(n103));
   INVX1 U267 (.A(\fiforeg[6][6] ),
	.Y(n259));
   MUX2X1 U268 (.A(wdata[6]),
	.B(N18),
	.S(wenable),
	.Y(n191));
   MUX2X1 U269 (.A(n260),
	.B(n193),
	.S(FE_OFN22_n183),
	.Y(n102));
   INVX1 U270 (.A(\fiforeg[6][5] ),
	.Y(n260));
   MUX2X1 U271 (.A(wdata[5]),
	.B(N19),
	.S(wenable),
	.Y(n193));
   MUX2X1 U272 (.A(n261),
	.B(n195),
	.S(FE_OFN22_n183),
	.Y(n101));
   INVX1 U273 (.A(\fiforeg[6][4] ),
	.Y(n261));
   MUX2X1 U274 (.A(wdata[4]),
	.B(N20),
	.S(wenable),
	.Y(n195));
   MUX2X1 U275 (.A(n262),
	.B(n197),
	.S(FE_OFN22_n183),
	.Y(n100));
   NAND3X1 U276 (.A(N14),
	.B(n212),
	.C(N15),
	.Y(n183));
   INVX2 U277 (.A(FE_OFN5_waddr_0),
	.Y(n212));
   INVX1 U278 (.A(\fiforeg[6][3] ),
	.Y(n262));
   MUX2X1 U279 (.A(wdata[3]),
	.B(N21),
	.S(wenable),
	.Y(n197));
endmodule

module write_ptr (
	wclk, 
	rst_n, 
	wenable, 
	wptr, 
	wptr_nxt);
   input wclk;
   input rst_n;
   input wenable;
   output [3:0] wptr;
   output [3:0] wptr_nxt;

   // Internal wires
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire [2:0] binary_nxt;
   wire [3:0] binary_r;

   DFFSR \binary_r_reg[0]  (.CLK(wclk),
	.D(binary_nxt[0]),
	.Q(binary_r[0]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \binary_r_reg[1]  (.CLK(wclk),
	.D(binary_nxt[1]),
	.Q(binary_r[1]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \binary_r_reg[2]  (.CLK(wclk),
	.D(binary_nxt[2]),
	.Q(binary_r[2]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \binary_r_reg[3]  (.CLK(wclk),
	.D(wptr_nxt[3]),
	.Q(binary_r[3]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \gray_r_reg[3]  (.CLK(wclk),
	.D(wptr_nxt[3]),
	.Q(wptr[3]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \gray_r_reg[2]  (.CLK(wclk),
	.D(wptr_nxt[2]),
	.Q(wptr[2]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \gray_r_reg[1]  (.CLK(wclk),
	.D(wptr_nxt[1]),
	.Q(wptr[1]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \gray_r_reg[0]  (.CLK(wclk),
	.D(wptr_nxt[0]),
	.Q(wptr[0]),
	.R(rst_n),
	.S(1'b1));
   XOR2X1 U11 (.A(wptr_nxt[3]),
	.B(binary_nxt[2]),
	.Y(wptr_nxt[2]));
   XNOR2X1 U12 (.A(n9),
	.B(binary_r[3]),
	.Y(wptr_nxt[3]));
   NAND2X1 U13 (.A(binary_r[2]),
	.B(n10),
	.Y(n9));
   XOR2X1 U14 (.A(binary_nxt[2]),
	.B(binary_nxt[1]),
	.Y(wptr_nxt[1]));
   XOR2X1 U15 (.A(binary_nxt[1]),
	.B(binary_nxt[0]),
	.Y(wptr_nxt[0]));
   XOR2X1 U16 (.A(n10),
	.B(binary_r[2]),
	.Y(binary_nxt[2]));
   INVX1 U17 (.A(n11),
	.Y(n10));
   NAND3X1 U18 (.A(binary_r[1]),
	.B(binary_r[0]),
	.C(wenable),
	.Y(n11));
   XNOR2X1 U19 (.A(n12),
	.B(binary_r[1]),
	.Y(binary_nxt[1]));
   NAND2X1 U20 (.A(wenable),
	.B(binary_r[0]),
	.Y(n12));
   XOR2X1 U21 (.A(binary_r[0]),
	.B(wenable),
	.Y(binary_nxt[0]));
endmodule

module write_fifo_ctrl (
	wclk, 
	rst_n, 
	wenable, 
	rptr, 
	wenable_fifo, 
	wptr, 
	waddr, 
	full_flag);
   input wclk;
   input rst_n;
   input wenable;
   input [3:0] rptr;
   output wenable_fifo;
   output [3:0] wptr;
   output [2:0] waddr;
   output full_flag;

   // Internal wires
   wire FE_OFN17_wenable_fifo;
   wire FE_OFN2_nfifo_full;
   wire \gray_wptr[2] ;
   wire N5;
   wire n2;
   wire n3;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire [3:0] wptr_nxt;
   wire [3:0] wrptr_r2;
   wire [3:0] wrptr_r1;

   BUFX2 FE_OFC17_wenable_fifo (.A(FE_OFN17_wenable_fifo),
	.Y(wenable_fifo));
   BUFX2 FE_OFC2_nfifo_full (.A(FE_OFN2_nfifo_full),
	.Y(full_flag));
   DFFSR \wrptr_r1_reg[3]  (.CLK(wclk),
	.D(rptr[3]),
	.Q(wrptr_r1[3]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \wrptr_r1_reg[2]  (.CLK(wclk),
	.D(rptr[2]),
	.Q(wrptr_r1[2]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \wrptr_r1_reg[1]  (.CLK(wclk),
	.D(rptr[1]),
	.Q(wrptr_r1[1]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \wrptr_r1_reg[0]  (.CLK(wclk),
	.D(rptr[0]),
	.Q(wrptr_r1[0]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \wrptr_r2_reg[3]  (.CLK(wclk),
	.D(wrptr_r1[3]),
	.Q(wrptr_r2[3]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \wrptr_r2_reg[2]  (.CLK(wclk),
	.D(wrptr_r1[2]),
	.Q(wrptr_r2[2]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \wrptr_r2_reg[1]  (.CLK(wclk),
	.D(wrptr_r1[1]),
	.Q(wrptr_r2[1]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \wrptr_r2_reg[0]  (.CLK(wclk),
	.D(wrptr_r1[0]),
	.Q(wrptr_r2[0]),
	.R(rst_n),
	.S(1'b1));
   DFFSR full_flag_r_reg (.CLK(wclk),
	.D(N5),
	.Q(FE_OFN2_nfifo_full),
	.R(rst_n),
	.S(1'b1));
   DFFSR \waddr_reg[2]  (.CLK(wclk),
	.D(\gray_wptr[2] ),
	.Q(waddr[2]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \waddr_reg[1]  (.CLK(wclk),
	.D(wptr_nxt[1]),
	.Q(waddr[1]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \waddr_reg[0]  (.CLK(wclk),
	.D(wptr_nxt[0]),
	.Q(waddr[0]),
	.R(rst_n),
	.S(1'b1));
   write_ptr WPU1 (.wclk(wclk),
	.rst_n(rst_n),
	.wenable(wenable_fifo),
	.wptr(wptr),
	.wptr_nxt(wptr_nxt));
   NOR2X1 U16 (.A(full_flag),
	.B(n2),
	.Y(FE_OFN17_wenable_fifo));
   INVX1 U17 (.A(wenable),
	.Y(n2));
   NOR2X1 U18 (.A(n3),
	.B(n16),
	.Y(N5));
   NAND2X1 U19 (.A(n17),
	.B(n18),
	.Y(n16));
   XOR2X1 U20 (.A(n19),
	.B(\gray_wptr[2] ),
	.Y(n18));
   XOR2X1 U21 (.A(wptr_nxt[3]),
	.B(wptr_nxt[2]),
	.Y(\gray_wptr[2] ));
   XNOR2X1 U22 (.A(wrptr_r2[3]),
	.B(wrptr_r2[2]),
	.Y(n19));
   XNOR2X1 U23 (.A(wrptr_r2[1]),
	.B(wptr_nxt[1]),
	.Y(n17));
   NAND2X1 U24 (.A(n20),
	.B(n21),
	.Y(n3));
   XOR2X1 U25 (.A(wrptr_r2[3]),
	.B(wptr_nxt[3]),
	.Y(n21));
   XNOR2X1 U26 (.A(wrptr_r2[0]),
	.B(wptr_nxt[0]),
	.Y(n20));
endmodule

module read_ptr (
	rclk, 
	rst_n, 
	renable, 
	rptr, 
	rptr_nxt);
   input rclk;
   input rst_n;
   input renable;
   output [3:0] rptr;
   output [3:0] rptr_nxt;

   // Internal wires
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire [2:0] binary_nxt;
   wire [3:0] binary_r;

   DFFSR \binary_r_reg[0]  (.CLK(rclk),
	.D(binary_nxt[0]),
	.Q(binary_r[0]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \binary_r_reg[1]  (.CLK(rclk),
	.D(binary_nxt[1]),
	.Q(binary_r[1]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \binary_r_reg[2]  (.CLK(rclk),
	.D(binary_nxt[2]),
	.Q(binary_r[2]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \binary_r_reg[3]  (.CLK(rclk),
	.D(rptr_nxt[3]),
	.Q(binary_r[3]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \gray_r_reg[3]  (.CLK(rclk),
	.D(rptr_nxt[3]),
	.Q(rptr[3]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \gray_r_reg[2]  (.CLK(rclk),
	.D(rptr_nxt[2]),
	.Q(rptr[2]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \gray_r_reg[1]  (.CLK(rclk),
	.D(rptr_nxt[1]),
	.Q(rptr[1]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \gray_r_reg[0]  (.CLK(rclk),
	.D(rptr_nxt[0]),
	.Q(rptr[0]),
	.R(rst_n),
	.S(1'b1));
   XOR2X1 U11 (.A(rptr_nxt[3]),
	.B(binary_nxt[2]),
	.Y(rptr_nxt[2]));
   XNOR2X1 U12 (.A(n9),
	.B(binary_r[3]),
	.Y(rptr_nxt[3]));
   NAND2X1 U13 (.A(binary_r[2]),
	.B(n10),
	.Y(n9));
   XOR2X1 U14 (.A(binary_nxt[2]),
	.B(binary_nxt[1]),
	.Y(rptr_nxt[1]));
   XOR2X1 U15 (.A(binary_nxt[1]),
	.B(binary_nxt[0]),
	.Y(rptr_nxt[0]));
   XOR2X1 U16 (.A(n10),
	.B(binary_r[2]),
	.Y(binary_nxt[2]));
   INVX1 U17 (.A(n11),
	.Y(n10));
   NAND3X1 U18 (.A(binary_r[1]),
	.B(binary_r[0]),
	.C(renable),
	.Y(n11));
   XNOR2X1 U19 (.A(n12),
	.B(binary_r[1]),
	.Y(binary_nxt[1]));
   NAND2X1 U20 (.A(renable),
	.B(binary_r[0]),
	.Y(n12));
   XOR2X1 U21 (.A(binary_r[0]),
	.B(renable),
	.Y(binary_nxt[0]));
endmodule

module read_fifo_ctrl (
	rclk, 
	rst_n, 
	renable, 
	wptr, 
	rptr, 
	raddr, 
	empty_flag);
   input rclk;
   input rst_n;
   input renable;
   input [3:0] wptr;
   output [3:0] rptr;
   output [2:0] raddr;
   output empty_flag;

   // Internal wires
   wire FE_OFN1_nfifo_empty;
   wire renable_p2;
   wire \gray_rptr[2] ;
   wire N3;
   wire n2;
   wire n3;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire [3:0] rptr_nxt;
   wire [3:0] rwptr_r2;
   wire [3:0] rwptr_r1;

   BUFX2 FE_OFC1_nfifo_empty (.A(FE_OFN1_nfifo_empty),
	.Y(empty_flag));
   DFFSR \rwptr_r1_reg[3]  (.CLK(rclk),
	.D(wptr[3]),
	.Q(rwptr_r1[3]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \rwptr_r1_reg[2]  (.CLK(rclk),
	.D(wptr[2]),
	.Q(rwptr_r1[2]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \rwptr_r1_reg[1]  (.CLK(rclk),
	.D(wptr[1]),
	.Q(rwptr_r1[1]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \rwptr_r1_reg[0]  (.CLK(rclk),
	.D(wptr[0]),
	.Q(rwptr_r1[0]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \rwptr_r2_reg[3]  (.CLK(rclk),
	.D(rwptr_r1[3]),
	.Q(rwptr_r2[3]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \rwptr_r2_reg[2]  (.CLK(rclk),
	.D(rwptr_r1[2]),
	.Q(rwptr_r2[2]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \rwptr_r2_reg[1]  (.CLK(rclk),
	.D(rwptr_r1[1]),
	.Q(rwptr_r2[1]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \rwptr_r2_reg[0]  (.CLK(rclk),
	.D(rwptr_r1[0]),
	.Q(rwptr_r2[0]),
	.R(rst_n),
	.S(1'b1));
   DFFSR empty_flag_r_reg (.CLK(rclk),
	.D(N3),
	.Q(FE_OFN1_nfifo_empty),
	.R(1'b1),
	.S(rst_n));
   DFFSR \raddr_reg[2]  (.CLK(rclk),
	.D(\gray_rptr[2] ),
	.Q(raddr[2]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \raddr_reg[1]  (.CLK(rclk),
	.D(rptr_nxt[1]),
	.Q(raddr[1]),
	.R(rst_n),
	.S(1'b1));
   DFFSR \raddr_reg[0]  (.CLK(rclk),
	.D(rptr_nxt[0]),
	.Q(raddr[0]),
	.R(rst_n),
	.S(1'b1));
   read_ptr RPU1 (.rclk(rclk),
	.rst_n(rst_n),
	.renable(renable_p2),
	.rptr(rptr),
	.rptr_nxt(rptr_nxt));
   NOR2X1 U15 (.A(empty_flag),
	.B(renable),
	.Y(renable_p2));
   NOR2X1 U17 (.A(n2),
	.B(n3),
	.Y(N3));
   NAND2X1 U18 (.A(n16),
	.B(n17),
	.Y(n3));
   XOR2X1 U19 (.A(n18),
	.B(\gray_rptr[2] ),
	.Y(n17));
   XOR2X1 U20 (.A(rptr_nxt[3]),
	.B(rptr_nxt[2]),
	.Y(\gray_rptr[2] ));
   XNOR2X1 U21 (.A(rwptr_r2[3]),
	.B(rwptr_r2[2]),
	.Y(n18));
   XNOR2X1 U22 (.A(rwptr_r2[1]),
	.B(rptr_nxt[1]),
	.Y(n16));
   NAND2X1 U23 (.A(n19),
	.B(n20),
	.Y(n2));
   XNOR2X1 U24 (.A(rwptr_r2[0]),
	.B(rptr_nxt[0]),
	.Y(n20));
   XNOR2X1 U25 (.A(rptr_nxt[3]),
	.B(rwptr_r2[3]),
	.Y(n19));
endmodule

module fifo (
	r_clk, 
	w_clk, 
	n_rst, 
	r_enable, 
	w_enable, 
	w_data, 
	r_data, 
	empty, 
	full);
   input r_clk;
   input w_clk;
   input n_rst;
   input r_enable;
   input w_enable;
   input [7:0] w_data;
   output [7:0] r_data;
   output empty;
   output full;

   // Internal wires
   wire wenable_fifo;
   wire [2:0] waddr;
   wire [2:0] raddr;
   wire [3:0] rptr;
   wire [3:0] wptr;

   fiforam UFIFORAM (.wclk(w_clk),
	.wenable(wenable_fifo),
	.waddr(waddr),
	.raddr(raddr),
	.wdata(w_data),
	.rdata(r_data));
   write_fifo_ctrl UWFC (.wclk(w_clk),
	.rst_n(n_rst),
	.wenable(w_enable),
	.rptr(rptr),
	.wenable_fifo(wenable_fifo),
	.wptr(wptr),
	.waddr(waddr),
	.full_flag(full));
   read_fifo_ctrl URFC (.rclk(r_clk),
	.rst_n(n_rst),
	.renable(r_enable),
	.wptr(wptr),
	.rptr(rptr),
	.raddr(raddr),
	.empty_flag(empty));
endmodule

module lab7_tx_fifo (
	clk, 
	n_rst, 
	read_done, 
	read_data, 
	fifo_empty, 
	fifo_full, 
	write_enable, 
	write_data);
   input clk;
   input n_rst;
   input read_done;
   output [7:0] read_data;
   output fifo_empty;
   output fifo_full;
   input write_enable;
   input [7:0] write_data;

   fifo IP_FIFO (.r_clk(clk),
	.w_clk(clk),
	.n_rst(n_rst),
	.r_enable(read_done),
	.w_enable(write_enable),
	.w_data(write_data),
	.r_data(read_data),
	.empty(fifo_empty),
	.full(fifo_full));
endmodule

module lab7_timer (
	clk, 
	n_rst, 
	start, 
	stop, 
	shift_enable, 
	bit_done);
   input clk;
   input n_rst;
   input start;
   input stop;
   output shift_enable;
   output bit_done;

   // Internal wires
   wire N73;
   wire N82;
   wire n32;
   wire n33;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire [1:0] curr_state;
   wire [2:0] clk_cnt;
   wire [2:0] nxt_clk_cnt;

   assign shift_enable = N73 ;
   assign bit_done = N82 ;

   DFFSR \curr_state_reg[0]  (.CLK(clk),
	.D(n33),
	.Q(curr_state[0]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_state_reg[1]  (.CLK(clk),
	.D(n32),
	.Q(curr_state[1]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \clk_cnt_reg[0]  (.CLK(clk),
	.D(nxt_clk_cnt[0]),
	.Q(clk_cnt[0]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \clk_cnt_reg[1]  (.CLK(clk),
	.D(nxt_clk_cnt[1]),
	.Q(clk_cnt[1]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \clk_cnt_reg[2]  (.CLK(clk),
	.D(nxt_clk_cnt[2]),
	.Q(clk_cnt[2]),
	.R(n_rst),
	.S(1'b1));
   NOR2X1 U8 (.A(n1),
	.B(n2),
	.Y(nxt_clk_cnt[2]));
   MUX2X1 U9 (.A(n3),
	.B(clk_cnt[2]),
	.S(n4),
	.Y(n2));
   MUX2X1 U10 (.A(n6),
	.B(n5),
	.S(clk_cnt[1]),
	.Y(nxt_clk_cnt[1]));
   INVX1 U11 (.A(nxt_clk_cnt[0]),
	.Y(n6));
   NAND2X1 U12 (.A(clk_cnt[0]),
	.B(n7),
	.Y(n5));
   NOR2X1 U13 (.A(n1),
	.B(clk_cnt[0]),
	.Y(nxt_clk_cnt[0]));
   OAI21X1 U14 (.A(n7),
	.B(n13),
	.C(n14),
	.Y(n33));
   AOI22X1 U15 (.A(curr_state[1]),
	.B(n15),
	.C(n16),
	.D(n17),
	.Y(n14));
   OAI22X1 U16 (.A(n4),
	.B(n18),
	.C(n19),
	.D(n20),
	.Y(n15));
   INVX1 U17 (.A(n21),
	.Y(n19));
   INVX1 U18 (.A(start),
	.Y(n13));
   INVX1 U19 (.A(n1),
	.Y(n7));
   NOR2X1 U20 (.A(curr_state[0]),
	.B(curr_state[1]),
	.Y(n1));
   OAI21X1 U21 (.A(n22),
	.B(n17),
	.C(n23),
	.Y(n32));
   OAI21X1 U22 (.A(n20),
	.B(n21),
	.C(curr_state[1]),
	.Y(n23));
   NAND2X1 U23 (.A(n4),
	.B(n18),
	.Y(n21));
   INVX1 U24 (.A(n3),
	.Y(n18));
   NOR2X1 U25 (.A(n24),
	.B(clk_cnt[2]),
	.Y(n3));
   XOR2X1 U26 (.A(clk_cnt[1]),
	.B(clk_cnt[0]),
	.Y(n24));
   INVX1 U27 (.A(stop),
	.Y(n17));
   INVX1 U28 (.A(n25),
	.Y(N82));
   NOR2X1 U29 (.A(n22),
	.B(n25),
	.Y(N73));
   NAND2X1 U30 (.A(clk_cnt[2]),
	.B(n4),
	.Y(n25));
   AND2X1 U31 (.A(clk_cnt[1]),
	.B(clk_cnt[0]),
	.Y(n4));
   INVX1 U32 (.A(n16),
	.Y(n22));
   NOR2X1 U33 (.A(n20),
	.B(curr_state[1]),
	.Y(n16));
   INVX1 U34 (.A(curr_state[0]),
	.Y(n20));
endmodule

module lab7_tcu (
	clk, 
	n_rst, 
	transmit, 
	bit_done, 
	bus_mode, 
	stop, 
	start, 
	sync, 
	read_done, 
	tx_sel, 
	tx_enable_0, 
	load_data_0, 
	tx_enable_1, 
	load_data_1);
   input clk;
   input n_rst;
   input transmit;
   input bit_done;
   output [1:0] bus_mode;
   output stop;
   output start;
   output sync;
   output read_done;
   output tx_sel;
   output tx_enable_0;
   output load_data_0;
   output tx_enable_1;
   output load_data_1;

   // Internal wires
   wire FE_PHN26_ntransmit;
   wire FE_OFN15_curr_state_1;
   wire n86;
   wire n88;
   wire n90;
   wire n93;
   wire n94;
   wire n95;
   wire n96;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n36;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire n59;
   wire n60;
   wire n61;
   wire n62;
   wire n63;
   wire n64;
   wire n65;
   wire n66;
   wire n67;
   wire n68;
   wire n69;
   wire n70;
   wire n71;
   wire n72;
   wire [3:0] curr_state;
   wire [2:0] bit_cnt;

   assign tx_enable_1 = tx_sel ;

   CLKBUF3 FE_PHC26_ntransmit (.A(transmit),
	.Y(FE_PHN26_ntransmit));
   BUFX2 FE_OFC15_curr_state_1 (.A(curr_state[1]),
	.Y(FE_OFN15_curr_state_1));
   DFFSR \bit_cnt_reg[0]  (.CLK(clk),
	.D(n90),
	.Q(bit_cnt[0]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \bit_cnt_reg[1]  (.CLK(clk),
	.D(n88),
	.Q(bit_cnt[1]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \bit_cnt_reg[2]  (.CLK(clk),
	.D(n86),
	.Q(bit_cnt[2]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_state_reg[0]  (.CLK(clk),
	.D(n96),
	.Q(curr_state[0]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_state_reg[2]  (.CLK(clk),
	.D(n94),
	.Q(curr_state[2]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_state_reg[1]  (.CLK(clk),
	.D(n95),
	.Q(curr_state[1]),
	.R(n_rst),
	.S(1'b1));
   DFFSR \curr_state_reg[3]  (.CLK(clk),
	.D(n93),
	.Q(curr_state[3]),
	.R(n_rst),
	.S(1'b1));
   NAND3X1 U3 (.A(n1),
	.B(n2),
	.C(n3),
	.Y(tx_sel));
   INVX1 U4 (.A(n4),
	.Y(n3));
   OAI21X1 U5 (.A(n5),
	.B(n6),
	.C(n7),
	.Y(n4));
   OAI21X1 U6 (.A(curr_state[2]),
	.B(n8),
	.C(n9),
	.Y(tx_enable_0));
   AOI21X1 U7 (.A(n10),
	.B(n5),
	.C(n11),
	.Y(n9));
   INVX1 U9 (.A(n13),
	.Y(bus_mode[1]));
   INVX1 U10 (.A(n14),
	.Y(sync));
   MUX2X1 U11 (.A(n16),
	.B(n15),
	.S(n17),
	.Y(n96));
   NOR2X1 U12 (.A(n18),
	.B(n19),
	.Y(n15));
   OAI21X1 U13 (.A(n20),
	.B(n21),
	.C(n22),
	.Y(n19));
   MUX2X1 U14 (.A(n24),
	.B(n23),
	.S(n25),
	.Y(n22));
   NAND2X1 U15 (.A(n26),
	.B(n27),
	.Y(n24));
   INVX1 U16 (.A(n1),
	.Y(n23));
   INVX1 U17 (.A(n28),
	.Y(n20));
   NAND3X1 U18 (.A(n29),
	.B(n30),
	.C(n7),
	.Y(n18));
   INVX1 U19 (.A(load_data_1),
	.Y(n29));
   NAND2X1 U20 (.A(n31),
	.B(n30),
	.Y(n95));
   INVX1 U21 (.A(start),
	.Y(n30));
   NOR2X1 U22 (.A(n26),
	.B(curr_state[0]),
	.Y(start));
   MUX2X1 U23 (.A(FE_OFN15_curr_state_1),
	.B(n32),
	.S(n17),
	.Y(n31));
   OR2X1 U24 (.A(n33),
	.B(n34),
	.Y(n32));
   OAI21X1 U25 (.A(n35),
	.B(n36),
	.C(n37),
	.Y(n34));
   INVX1 U26 (.A(n38),
	.Y(n37));
   OAI21X1 U27 (.A(n39),
	.B(n40),
	.C(n41),
	.Y(n33));
   AND2X1 U28 (.A(n14),
	.B(n42),
	.Y(n41));
   INVX1 U29 (.A(n43),
	.Y(n39));
   OAI21X1 U30 (.A(n27),
	.B(n25),
	.C(n1),
	.Y(n43));
   OAI21X1 U31 (.A(n44),
	.B(n17),
	.C(n45),
	.Y(n94));
   AND2X1 U32 (.A(n46),
	.B(n47),
	.Y(n45));
   OAI21X1 U33 (.A(n17),
	.B(n48),
	.C(curr_state[2]),
	.Y(n46));
   AOI21X1 U34 (.A(n35),
	.B(n49),
	.C(n38),
	.Y(n44));
   OAI21X1 U35 (.A(FE_PHN26_ntransmit),
	.B(n27),
	.C(n36),
	.Y(n49));
   INVX1 U36 (.A(n48),
	.Y(n36));
   OAI21X1 U37 (.A(n16),
	.B(n26),
	.C(n1),
	.Y(n48));
   NAND3X1 U38 (.A(n50),
	.B(n51),
	.C(n52),
	.Y(n93));
   AOI21X1 U39 (.A(curr_state[3]),
	.B(n17),
	.C(n53),
	.Y(n52));
   OAI21X1 U40 (.A(n1),
	.B(n54),
	.C(n42),
	.Y(n53));
   NAND2X1 U41 (.A(n35),
	.B(n40),
	.Y(n54));
   INVX1 U42 (.A(n25),
	.Y(n35));
   NAND3X1 U43 (.A(bit_cnt[1]),
	.B(bit_cnt[0]),
	.C(bit_cnt[2]),
	.Y(n25));
   OAI21X1 U44 (.A(n21),
	.B(n55),
	.C(n56),
	.Y(n17));
   OAI21X1 U45 (.A(n38),
	.B(n57),
	.C(n58),
	.Y(n56));
   NAND2X1 U46 (.A(n7),
	.B(n13),
	.Y(n57));
   NAND3X1 U47 (.A(curr_state[3]),
	.B(FE_OFN15_curr_state_1),
	.C(n59),
	.Y(n13));
   NOR2X1 U48 (.A(curr_state[0]),
	.B(n60),
	.Y(n59));
   OAI21X1 U49 (.A(n16),
	.B(n6),
	.C(n61),
	.Y(n38));
   AOI21X1 U50 (.A(n11),
	.B(FE_OFN15_curr_state_1),
	.C(stop),
	.Y(n61));
   NAND2X1 U51 (.A(n28),
	.B(n40),
	.Y(n55));
   INVX1 U52 (.A(transmit),
	.Y(n40));
   INVX1 U53 (.A(n62),
	.Y(n21));
   NOR2X1 U54 (.A(stop),
	.B(n63),
	.Y(n51));
   OAI21X1 U55 (.A(n6),
	.B(n5),
	.C(n64),
	.Y(stop));
   NAND3X1 U56 (.A(n28),
	.B(curr_state[2]),
	.C(curr_state[3]),
	.Y(n64));
   AND2X1 U57 (.A(n27),
	.B(n7),
	.Y(n50));
   NAND2X1 U58 (.A(n11),
	.B(n8),
	.Y(n27));
   XNOR2X1 U59 (.A(n58),
	.B(bit_cnt[0]),
	.Y(n90));
   INVX1 U60 (.A(bit_done),
	.Y(n58));
   XNOR2X1 U61 (.A(bit_cnt[1]),
	.B(n65),
	.Y(n88));
   XOR2X1 U62 (.A(bit_cnt[2]),
	.B(n66),
	.Y(n86));
   NOR2X1 U63 (.A(n67),
	.B(n65),
	.Y(n66));
   NAND2X1 U64 (.A(bit_done),
	.B(bit_cnt[0]),
	.Y(n65));
   INVX1 U65 (.A(bit_cnt[1]),
	.Y(n67));
   NAND2X1 U66 (.A(n14),
	.B(n2),
	.Y(load_data_0));
   NAND3X1 U67 (.A(curr_state[0]),
	.B(n8),
	.C(n62),
	.Y(n14));
   INVX1 U68 (.A(FE_OFN15_curr_state_1),
	.Y(n8));
   OR2X1 U69 (.A(n68),
	.B(n69),
	.Y(bus_mode[0]));
   NAND3X1 U70 (.A(n6),
	.B(n26),
	.C(n7),
	.Y(n69));
   NAND3X1 U71 (.A(n28),
	.B(n60),
	.C(curr_state[3]),
	.Y(n7));
   NAND2X1 U72 (.A(n62),
	.B(FE_OFN15_curr_state_1),
	.Y(n26));
   NOR2X1 U73 (.A(curr_state[3]),
	.B(curr_state[2]),
	.Y(n62));
   INVX1 U74 (.A(n10),
	.Y(n6));
   NOR2X1 U75 (.A(n60),
	.B(FE_OFN15_curr_state_1),
	.Y(n10));
   NAND3X1 U76 (.A(n70),
	.B(read_done),
	.C(n1),
	.Y(n68));
   NAND3X1 U77 (.A(n71),
	.B(n16),
	.C(FE_OFN15_curr_state_1),
	.Y(n1));
   INVX1 U78 (.A(curr_state[0]),
	.Y(n16));
   NOR2X1 U79 (.A(n63),
	.B(load_data_1),
	.Y(read_done));
   NAND2X1 U80 (.A(n42),
	.B(n47),
	.Y(load_data_1));
   NAND2X1 U81 (.A(n28),
	.B(n71),
	.Y(n47));
   NOR2X1 U82 (.A(FE_OFN15_curr_state_1),
	.B(curr_state[0]),
	.Y(n28));
   NAND3X1 U83 (.A(curr_state[3]),
	.B(FE_OFN15_curr_state_1),
	.C(n72),
	.Y(n42));
   NOR2X1 U84 (.A(curr_state[2]),
	.B(curr_state[0]),
	.Y(n72));
   INVX1 U85 (.A(n2),
	.Y(n63));
   NAND3X1 U86 (.A(curr_state[0]),
	.B(n71),
	.C(FE_OFN15_curr_state_1),
	.Y(n2));
   NOR2X1 U87 (.A(n60),
	.B(curr_state[3]),
	.Y(n71));
   INVX2 U88 (.A(curr_state[2]),
	.Y(n60));
   INVX1 U89 (.A(n11),
	.Y(n70));
   NOR2X1 U90 (.A(n5),
	.B(curr_state[2]),
	.Y(n11));
   NAND2X1 U91 (.A(curr_state[3]),
	.B(curr_state[0]),
	.Y(n5));
endmodule

module lab7_usb_transmitter (
	clk, 
	n_rst, 
	d_plus, 
	d_minus, 
	transmit, 
	write_enable, 
	write_data, 
	fifo_empty, 
	fifo_full);
   input clk;
   input n_rst;
   output d_plus;
   output d_minus;
   input transmit;
   input write_enable;
   input [7:0] write_data;
   output fifo_empty;
   output fifo_full;

   // Internal wires
   wire tx_sel_int;
   wire tx_out_0_int;
   wire tx_out_1_int;
   wire sync_int;
   wire tx_value_int;
   wire shift_enable_int;
   wire tx_enable_0_int;
   wire load_data_0_int;
   wire tx_enable_1_int;
   wire load_data_1_int;
   wire read_done_int;
   wire start_int;
   wire stop_int;
   wire bit_done_int;
   wire n1;
   wire n2;
   wire n3;
   wire [7:0] tx_data_int;
   wire [7:0] read_data_int;
   wire [1:0] bus_mode_int;

   lab7_out_ctrl OCTRL (.clk(clk),
	.n_rst(n_rst),
	.d_plus(d_plus),
	.d_minus(d_minus),
	.bus_mode(bus_mode_int),
	.tx_value(tx_value_int));
   lab7_encoder ENC (.clk(clk),
	.n_rst(n_rst),
	.tx_bit(n3),
	.shift_enable(shift_enable_int),
	.tx_value(tx_value_int));
   lab7_tx_sr_1 T_SR_0 (.clk(clk),
	.n_rst(n_rst),
	.shift_enable(shift_enable_int),
	.tx_enable(tx_enable_0_int),
	.tx_data(tx_data_int),
	.load_data(load_data_0_int),
	.tx_out(tx_out_0_int));
   lab7_tx_sr_0 T_SR_1 (.clk(clk),
	.n_rst(n_rst),
	.shift_enable(shift_enable_int),
	.tx_enable(tx_enable_1_int),
	.tx_data(tx_data_int),
	.load_data(load_data_1_int),
	.tx_out(tx_out_1_int));
   lab7_tx_fifo T_FIFO (.clk(clk),
	.n_rst(n_rst),
	.read_done(read_done_int),
	.read_data(read_data_int),
	.fifo_empty(fifo_empty),
	.fifo_full(fifo_full),
	.write_enable(write_enable),
	.write_data(write_data));
   lab7_timer TIM (.clk(clk),
	.n_rst(n_rst),
	.start(start_int),
	.stop(stop_int),
	.shift_enable(shift_enable_int),
	.bit_done(bit_done_int));
   lab7_tcu CTRL (.clk(clk),
	.n_rst(n_rst),
	.transmit(transmit),
	.bit_done(bit_done_int),
	.bus_mode(bus_mode_int),
	.stop(stop_int),
	.start(start_int),
	.sync(sync_int),
	.read_done(read_done_int),
	.tx_sel(tx_sel_int),
	.tx_enable_0(tx_enable_0_int),
	.load_data_0(load_data_0_int),
	.tx_enable_1(tx_enable_1_int),
	.load_data_1(load_data_1_int));
   OR2X1 U3 (.A(read_data_int[7]),
	.B(sync_int),
	.Y(tx_data_int[7]));
   AND2X1 U4 (.A(read_data_int[6]),
	.B(n1),
	.Y(tx_data_int[6]));
   AND2X1 U5 (.A(read_data_int[5]),
	.B(n1),
	.Y(tx_data_int[5]));
   AND2X1 U6 (.A(read_data_int[4]),
	.B(n1),
	.Y(tx_data_int[4]));
   AND2X1 U7 (.A(read_data_int[3]),
	.B(n1),
	.Y(tx_data_int[3]));
   AND2X1 U8 (.A(read_data_int[2]),
	.B(n1),
	.Y(tx_data_int[2]));
   AND2X1 U9 (.A(read_data_int[1]),
	.B(n1),
	.Y(tx_data_int[1]));
   AND2X1 U10 (.A(read_data_int[0]),
	.B(n1),
	.Y(tx_data_int[0]));
   INVX1 U11 (.A(sync_int),
	.Y(n1));
   INVX1 U12 (.A(n2),
	.Y(n3));
   MUX2X1 U13 (.A(tx_out_1_int),
	.B(tx_out_0_int),
	.S(tx_sel_int),
	.Y(n2));
endmodule

module lab7_layout_design_t (
	clk, 
	n_rst, 
	d_plus, 
	d_minus, 
	transmit, 
	write_enable, 
	write_data, 
	fifo_empty, 
	fifo_full);
   input clk;
   input n_rst;
   output d_plus;
   output d_minus;
   input transmit;
   input write_enable;
   input [7:0] write_data;
   output fifo_empty;
   output fifo_full;

   lab7_usb_transmitter LD (.clk(clk),
	.n_rst(n_rst),
	.d_plus(d_plus),
	.d_minus(d_minus),
	.transmit(transmit),
	.write_enable(write_enable),
	.write_data(write_data),
	.fifo_empty(fifo_empty),
	.fifo_full(fifo_full));
endmodule

module lab7_layout_design (
	clk, 
	n_rst, 
	d_plus, 
	d_minus, 
	transmit, 
	write_enable, 
	write_data, 
	fifo_empty, 
	fifo_full);
   input clk;
   input n_rst;
   output d_plus;
   output d_minus;
   input transmit;
   input write_enable;
   input [7:0] write_data;
   output fifo_empty;
   output fifo_full;

   // Internal wires
   wire nclk;
   wire nn_rst;
   wire ntransmit;
   wire nwrite_enable;
   wire nd_plus;
   wire nd_minus;
   wire nfifo_empty;
   wire nfifo_full;
   wire [7:0] nwrite_data;

   lab7_layout_design_t I0 (.clk(nclk),
	.n_rst(nn_rst),
	.d_plus(nd_plus),
	.d_minus(nd_minus),
	.transmit(ntransmit),
	.write_enable(nwrite_enable),
	.write_data(nwrite_data),
	.fifo_empty(nfifo_empty),
	.fifo_full(nfifo_full));
   PADOUT U1 (.DO(nd_minus),
	.YPAD(d_minus));
   PADOUT U2 (.DO(nd_plus),
	.YPAD(d_plus));
   PADOUT U3 (.DO(nfifo_empty),
	.YPAD(fifo_empty));
   PADOUT U4 (.DO(nfifo_full),
	.YPAD(fifo_full));
   PADINC U5 (.DI(nclk),
	.YPAD(clk));
   PADINC U6 (.DI(nn_rst),
	.YPAD(n_rst));
   PADINC U7 (.DI(ntransmit),
	.YPAD(transmit));
   PADINC U8 (.DI(nwrite_data[0]),
	.YPAD(write_data[0]));
   PADINC U9 (.DI(nwrite_data[1]),
	.YPAD(write_data[1]));
   PADINC U10 (.DI(nwrite_data[2]),
	.YPAD(write_data[2]));
   PADINC U11 (.DI(nwrite_data[3]),
	.YPAD(write_data[3]));
   PADINC U12 (.DI(nwrite_data[4]),
	.YPAD(write_data[4]));
   PADINC U13 (.DI(nwrite_data[5]),
	.YPAD(write_data[5]));
   PADINC U14 (.DI(nwrite_data[6]),
	.YPAD(write_data[6]));
   PADINC U15 (.DI(nwrite_data[7]),
	.YPAD(write_data[7]));
   PADINC U16 (.DI(nwrite_enable),
	.YPAD(write_enable));
endmodule

